# Copyright 2021 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, edited]
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-20.04
    env:
      CONTAINER_REGISTRY: "localhost:5001"
      IMAGE_REPO_PREFIX: halo
      CLUSTER_LOGS_DIR: cluster-logs
    steps:
      - name: Check out revision
        uses: actions/checkout@v3

      - name: Create cluster
        id: create-cluster
        run: |
          curl -LOJ https://kind.sigs.k8s.io/examples/kind-with-registry.sh
          chmod +x kind-with-registry.sh
          ./kind-with-registry.sh

      - name: Bazel build and test
        uses: world-federation-of-advertisers/actions/bazel-build-test@v1
        with:
          cache-version: 1
          workspace-path: .
          target-patterns: |
            //...
            //src/test/kotlin/org/wfanet/measurement/integration/k8s:LocalClusterCorrectnessTest
          build-options: |
            --compilation_mode=opt
            --host_platform=//build/platforms:ubuntu_20_04
            --define=container_registry=${{ env.CONTAINER_REGISTRY }}
            --define=image_repo_prefix=${{ env.IMAGE_REPO_PREFIX }}
            --define=image_tag=latest

      - name: Export cluster logs
        id: export-cluster-logs
        if: steps.create-cluster.outcome == 'success'
        run: |
          mkdir -p "$CLUSTER_LOGS_DIR"
          kind export logs "$CLUSTER_LOGS_DIR"

      - name: Upload cluster logs artifact
        if: steps.export-cluster-logs.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: cluster-logs
          path: ${{ env.CLUSTER_LOGS_DIR }}
