# Copyright 2023 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Configure Duchy"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag needed for configuration"
        type: string
        required: true
      kubectl_apply:
        description: "Apply the manifest to the cluster"
        required: false
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  create_k8s_manifest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_SECRETS }}

      # TODO(wfa-hkawalkar): applying manifest failing.
      - name: Apply secrets
        run: bazelisk run //src/main/k8s/testing/secretfiles:apply_kustomization

      # TODO(wfa-hkawalkar): import secrets to manifest from k8s secretsfile.
      # Create k8s manifest
      - name: Build K8s manifest
        run: |
          bazelisk build //src/main/k8s/dev:worker1_duchy_gke \
          --define k8s_duchy_secret_name=certs-and-configs \
          --define duchy_cert_id=SVVse4xWHL0 \
          --define duchy_storage_bucket=worker1-duchy \
          --define container_registry=${{ env.REGISTRY }} \
          --define image_repo_prefix=world-federation-of-advertisers/packages \
          --define image_tag=${{ inputs.image_tag }}

      # Apply manifest
      - name: apply k8s manifest
        if: inputs.kubectl_apply == true
        run: kubectl apply -f bazel-bin/src/main/k8s/dev/worker1_duchy_gke.yaml

